### ISSUE TITLE
Need Apple Mac version

### ISSUE THREAD

**Issue by TechExaminer** [letheanVPN/lethean-vpn#124]
Please add a version of Lethean that can run on a Mac computer.

**Comment by bodane** [comment]
@TechExaminer, Can you confirm which mac wallet you attempted to use of the lethean wallets and version?

Also any further information on the OSX version you are using and any outputs of the problem experienced would be quite helpful. Thanks.

**Comment by TechExaminer** [comment]
I was actually suggesting a Mac version for the Exit Node software. 

James Hannibal
The-Tech-Examiner.com

**Comment by bodane** [comment]
Thanks for clarifying. Should have looked at what your comment referred too!

**Comment by snider** [comment]
This is coming in the next few weeks.

**Comment by Snider** [comment]
V2/ letheanVPN/Lethean-Server will handle this fine; until then using a Docker install will get this working for you.
