### ISSUE TITLE
Receive error that haproxy must be 1.6.x, 1.7.x or 1.8.x but haproxy is updated during setup

### ISSUE THREAD

**Issue by muckee** [letheanVPN/lethean-vpn#126]
haproxy cannot be higher than 1.8, but when `easy-deploy-node.sh` is executed, haproxy is updated to version 2.0.13 on Ubuntu 20.04.

**Comment by ronnylov** [comment]
Try this:
https://github.com/LetheanMovement/lethean-vpn/issues/71

**Comment by Snider** [comment]
fixed with: https://github.com/letheanVPN/lethean-vpn/commit/75431ee10f6feccdcd4a9f56c9ea2fb0ac8861c8
