### ISSUE TITLE
lthn/chain:latest not found

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lethean-vpn#134]
Docker-compose references docker hub repository "lthn/chain:latest" which doesn't exist. Need to be republished.

----------

docker-compose up -d
Creating network "lethean-vpn_default" with the default driver
Creating volume "lethean-vpn_data" with default driver
Pulling blockchain (lthn/chain:)...
ERROR: manifest for lthn/chain:latest not found: manifest unknown: manifest unknown

**Comment by Snider** [comment]
https://github.com/letheanVPN/lethean-vpn/issues/134 even

**Comment by Snider** [comment]
@bodane https://hub.docker.com/repository/docker/lthn/chain/tags?page=1&ordering=last_updated

**Comment by bodane** [comment]
Resolved :) . Chain container does however stop after running. Will raise that being a separate issue along with logs.

```docker-compose up -d
Pulling blockchain (lthn/chain:)...
latest: Pulling from lthn/chain
a2abf6c4d29d: Pull complete
030d58ceaa11: Pull complete
Digest: sha256:ee7d56de0b372836a297b746ccff41c1992436219cabb6bcb5ea3dc8c2d5ee0f
Status: Downloaded newer image for lthn/chain:latest
Creating chain ... done
Creating dispatcher ... done

**Comment by Snider** [comment]
can you check if it is a composer or a dockerfile issue?

**Comment by bodane** [comment]
Sure. Will raise a new issue to track that and go from there.
