### ISSUE TITLE
Haproxy version 1.9 is not supported? Needed for Arch Linux

### ISSUE THREAD

**Issue by ronnylov** [letheanVPN/lethean-vpn#71]
Trying to install lethean-vpn on Arch Linux.

[lethe@de01 lethean-vpn]$ ./configure.sh --prefix /opt/lthn --client
Incompatible version of haproxy! You need 1.6.x, 1.7.x or 1.8.x version for now.
HA-Proxy version 1.9.4 2019/02/06 - https://haproxy.org/

**Comment by ronnylov** [comment]
I edited configure.sh to allow haproxy version 1.9. We'll see if some problems occur because of this.

```
if ! $HAPROXY_BIN -v | grep -qE "version 1.7|version 1.6|version 1.8|version 1.9"; then
    echo "Incompatible version of haproxy! You need 1.6.x, 1.7.x, 1.8.x or 1.9.x version for now."
    $HAPROXY_BIN -v
    exit 1
fi

```

**Comment by ronnylov** [comment]
Lethernet DE exit node is now using haproxy 1.9. So far it seems to work.

**Comment by limosek** [comment]
Should be fixed in https://github.com/LetheanMovement/lethean-vpn/pull/96
